sonar.projectKey=scheilch_opencloudtouch
sonar.organization=scheilscm
sonar.qualitygate.wait=true

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=opencloudtouch
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=apps/backend/src,apps/frontend/src

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

# Exclude test files from analysis
sonar.exclusions=**/tests/**,**/__tests__/**,**/*.test.*,**/pytest.ini,**/sonar-project.properties
